export const SET_NEW_DATA = 'SET_NEW_DATA';
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
export const SET_CHECKED_ROWS = 'SET_CHECKED_ROWS';
export const SET_NEW_CELL_VALUE = 'SET_NEW_CELL_VALUE';
export const SET_DATA_STRUCTURE = 'SET_DATA_STRUCTURE';
export const SORT_FILTERED_DATA = 'SORT_FILTERED_DATA';
